FROM fedora:42 AS builder

RUN dnf install -y \
    gcc \
    krb5-config \
    python3-devel \
    uv \
    clang \
    zlib-devel \
    && dnf clean all

WORKDIR /build

COPY pyproject.toml uv.lock* ./

RUN uv sync --all-extras --all-groups


FROM fedora:42

RUN dnf install -y \
    gcc \
    krb5-config \
    python3-devel \
    uv \
    clang \
    zlib-devel \
    && dnf clean all

ENV TERM=xterm-256color

WORKDIR /app
RUN mkdir -p /app/bind

CMD ["bash"]
