FROM fedora:latest

RUN mkdir -p /app/copy
RUN mkdir -p /app/bind

COPY . /app/copy

RUN dnf install -y \
    gcc \
    krb5-config \
    python3-devel \
    uv \
    && dnf clean all

# TODO: copy not used now, delete or use as one time copy when e2e testing
WORKDIR /app/copy
RUN uv sync --all-extras --all-groups

WORKDIR /app
