specfile_path: files/rpmeta.spec

jobs:
  - job: copr_build
    trigger: pull_request
    downstream_package_name: rpmeta-git
    targets:
      - fedora-all

  - job: copr_build
    trigger: commit
    branch: main
    downstream_package_name: rpmeta-git
    <<: &copr_rpmeta_repo_defaults
      targets:
        - fedora-all
      owner: "@copr"
      project: "rpmeta"
      list_on_homepage: True
      preserve_project: True

  - job: copr_build
    trigger: release
    <<: *copr_rpmeta_repo_defaults
