specfile_path: dist/rpmeta.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
    owner: "@copr"
    project: "rpmeta"
    branch: main
    list_on_homepage: True
    preserve_project: True
